import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { readFileSync } from 'fs';
import { doc, setDoc, getDoc, updateDoc, collection, addDoc, query, where, getDocs, deleteDoc, serverTimestamp, arrayUnion, increment, writeBatch } from 'firebase/firestore';
const env = await initializeTestEnvironment({ projectId: 'milkchat-915d4', firestore: { rules: readFileSync('firestore.rules','utf8'), host: '127.0.0.1', port: 8085 } });
const A = env.authenticatedContext('alice').firestore();
const B = env.authenticatedContext('bob').firestore();
const C = env.authenticatedContext('carol').firestore();
const anon = env.unauthenticatedContext().firestore();
let ok = 0, bad = 0;
async function t(name, p) { try { await p; ok++; console.log('ok  ', name); } catch (e) { bad++; console.log('FAIL', name, e.message.split('\n')[0]); } }
const prof = (u) => ({ username: u, usernameLower: u.toLowerCase(), displayName: u, bio: '', avatarUrl: null, verified: false, createdAt: serverTimestamp(), lastSeen: serverTimestamp() });
await t('create own profile', assertSucceeds(setDoc(doc(A,'users/alice'), prof('Alice'))));
await t('create profile verified=true denied', assertFails(setDoc(doc(B,'users/bob'), {...prof('Bob'), verified: true})));
await t('create bob profile', assertSucceeds(setDoc(doc(B,'users/bob'), prof('Bob'))));
await t('self-verify denied', assertFails(updateDoc(doc(A,'users/alice'), { verified: true })));
await t('edit own bio', assertSucceeds(updateDoc(doc(A,'users/alice'), { bio: 'hi' })));
await t('edit others profile denied', assertFails(updateDoc(doc(A,'users/bob'), { bio: 'x' })));
await t('anon read profile denied', assertFails(getDoc(doc(anon,'users/alice'))));
await t('search users', assertSucceeds(getDocs(query(collection(A,'users'), where('usernameLower','>=','b')))));
await t('claim username', assertSucceeds(setDoc(doc(A,'usernames/alice'), { uid: 'alice' })));
await t('claim username for other denied', assertFails(setDoc(doc(A,'usernames/x'), { uid: 'bob' })));
await t('get missing dm', assertSucceeds(getDoc(doc(A,'chats/dm_alice_bob'))));
await t('create dm', assertSucceeds(setDoc(doc(A,'chats/dm_alice_bob'), { kind:'direct', members:['alice','bob'], admins:[], createdBy:'alice', createdAt: serverTimestamp(), lastAt: serverTimestamp() })));
await t('dm forged id denied', assertFails(setDoc(doc(A,'chats/dm_alice_carol'), { kind:'direct', members:['alice','bob'], admins:[], createdBy:'alice' })));
await t('outsider reads dm denied', assertFails(getDoc(doc(C,'chats/dm_alice_bob'))));
await t('list my chats', assertSucceeds(getDocs(query(collection(B,'chats'), where('members','array-contains','bob')))));
const sendBatch = (db, chat, uid) => { const b = writeBatch(db); b.set(doc(collection(db, `chats/${chat}/messages`)), { senderId: uid, senderName: uid, text: 'hi', createdAt: serverTimestamp() }); b.update(doc(db,`chats/${chat}`), { lastMessage: { text:'hi', senderId: uid, senderName: uid }, lastAt: serverTimestamp(), [`readAt.${uid}`]: serverTimestamp(), 'unread.x': increment(1) }); return b.commit(); };
await t('member sends dm', assertSucceeds(sendBatch(B,'dm_alice_bob','bob')));
await t('outsider sends dm denied', assertFails(sendBatch(C,'dm_alice_bob','carol')));
await t('forged sender denied', assertFails(addDoc(collection(A,'chats/dm_alice_bob/messages'), { senderId:'bob', text:'x', createdAt: serverTimestamp() })));
await t('member reads messages', assertSucceeds(getDocs(collection(A,'chats/dm_alice_bob/messages'))));
await t('outsider reads messages denied', assertFails(getDocs(collection(C,'chats/dm_alice_bob/messages'))));
await t('create channel', assertSucceeds(setDoc(doc(A,'chats/ch1'), { kind:'channel', title:'Ch', members:['alice'], admins:['alice'], createdBy:'alice' })));
await t('create channel with others as admin denied', assertFails(setDoc(doc(A,'chats/ch2'), { kind:'channel', title:'Ch', members:['alice','bob'], admins:['alice','bob'], createdBy:'alice' })));
await t('create milkchat denied', assertFails(setDoc(doc(A,'chats/milkchat'), { kind:'channel', title:'X', members:['alice'], admins:['alice'], createdBy:'alice' })));
await t('bob subscribes channel', assertSucceeds(updateDoc(doc(B,'chats/ch1'), { members: arrayUnion('bob') })));
await t('bob adds carol denied', assertFails(updateDoc(doc(B,'chats/ch1'), { members: arrayUnion('carol') })));
await t('bob makes self admin denied', assertFails(updateDoc(doc(B,'chats/ch1'), { admins: arrayUnion('bob') })));
await t('subscriber posts in channel denied', assertFails(sendBatch(B,'ch1','bob')));
await t('admin posts in channel', assertSucceeds(sendBatch(A,'ch1','alice')));
await t('subscriber marks read', assertSucceeds(updateDoc(doc(B,'chats/ch1'), { 'unread.bob': 0, 'readAt.bob': serverTimestamp() })));
await t('subscriber renames channel denied', assertFails(updateDoc(doc(B,'chats/ch1'), { title: 'hack' })));
let msgs = []; await env.withSecurityRulesDisabled(async c => { msgs = (await getDocs(collection(c.firestore(),'chats/ch1/messages'))).docs.map(d=>d.id); });
await t('subscriber deletes admin msg denied', assertFails(deleteDoc(doc(B,`chats/ch1/messages/${msgs[0]}`))));
await t('admin edits own msg', assertSucceeds(updateDoc(doc(A,`chats/ch1/messages/${msgs[0]}`), { text:'edited', editedAt: serverTimestamp() })));
await t('admin deletes msg', assertSucceeds(deleteDoc(doc(A,`chats/ch1/messages/${msgs[0]}`))));
await t('bob leaves channel', assertSucceeds(updateDoc(doc(B,'chats/ch1'), { members: ['alice'] })));
await t('other settings denied', assertFails(getDoc(doc(B,'user_settings/alice/chats/ch1'))));
await t('own settings', assertSucceeds(setDoc(doc(A,'user_settings/alice/chats/ch1'), { pinned: true })));
await t('report', assertSucceeds(addDoc(collection(A,'reports'), { reporterId:'alice', chatId:'ch1' })));
await t('read reports denied', assertFails(getDocs(collection(A,'reports'))));
const S = env.authenticatedContext('staff', { staff: true }).firestore();
await t('staff reads reports', assertSucceeds(getDocs(collection(S,'reports'))));
await t('self-ban-field on create denied', assertFails(setDoc(doc(C,'users/carol'), {...prof('Carol'), banned: true})));
await t('create carol', assertSucceeds(setDoc(doc(C,'users/carol'), prof('Carol'))));
await t('user unbans self denied', assertFails(updateDoc(doc(C,'users/carol'), { banned: false })));
await t('user verifies other denied', assertFails(updateDoc(doc(A,'users/bob'), { verified: true })));
await t('staff verifies user', assertSucceeds(updateDoc(doc(S,'users/bob'), { verified: true })));
await t('staff edits bio denied', assertFails(updateDoc(doc(S,'users/bob'), { bio: 'x' })));
await t('staff bans carol', assertSucceeds(updateDoc(doc(S,'users/carol'), { banned: true })));
await t('banned creates group denied', assertFails(setDoc(doc(C,'chats/g9'), { kind:'group', title:'G', members:['carol'], admins:['carol'], createdBy:'carol' })));
await t('staff lists all chats', assertSucceeds(getDocs(query(collection(S,'chats'), where('kind','in',['group','channel'])))));
await t('user lists all chats denied', assertFails(getDocs(query(collection(A,'chats'), where('kind','in',['group','channel'])))));
await t('staff renames channel', assertSucceeds(updateDoc(doc(S,'chats/ch1'), { title: 'Renamed', verified: true })));
await t('admin sets chat verified denied', assertFails(updateDoc(doc(A,'chats/ch1'), { verified: false })));
await t('staff deletes chat', assertSucceeds(deleteDoc(doc(S,'chats/ch1'))));
await env.withSecurityRulesDisabled(async c => { await setDoc(doc(c.firestore(),'chats/g1'), { kind:'group', title:'G', members:['alice','carol'], admins:['alice'], createdBy:'alice' }); });
await t('banned sends message denied', assertFails(addDoc(collection(C,'chats/g1/messages'), { senderId:'carol', text:'x', createdAt: serverTimestamp() })));
await t('member sends message', assertSucceeds(addDoc(collection(A,'chats/g1/messages'), { senderId:'alice', text:'x', createdAt: serverTimestamp() })));
console.log(`\n${ok} passed, ${bad} failed`);
await env.cleanup(); process.exit(bad ? 1 : 0);
